#ifndef SIGNALGENERATOR_GLOBAL_H
#define SIGNALGENERATOR_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(SIGNALGENERATOR_LIB)
#  define SIGNALGENERATOR_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALGENERATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALGENERATOR_GLOBAL_H
