INSERT INTO IORChannel VALUES('CF1', 0, 0, 0);
INSERT INTO IORChannel VALUES('CF2', 0, 0, 1);
INSERT INTO IORChannel VALUES('CF4', 0, 0, 2);
INSERT INTO IORChannel VALUES('CF5', 0, 0, 3);
INSERT INTO IORChannel VALUES('CF7', 0, 0, 4);
INSERT INTO IORChannel VALUES('CF9', 0, 0, 5);
INSERT INTO IORChannel VALUES('DT', 0, 0, 6);
INSERT INTO IORChannel VALUES('QZN', 0, 0, 7);
INSERT INTO IORChannel VALUES('TBVDF1', 0, 1, 0);
INSERT INTO IORChannel VALUES('TBVDF2', 0, 1, 1);
INSERT INTO IORChannel VALUES('Not used 0', 0, 1, 2);
INSERT INTO IORChannel VALUES('QZ9', 0, 1, 3);
INSERT INTO IORChannel VALUES('CF8', 0, 1, 4);
INSERT INTO IORChannel VALUES('Vanne BD', 0, 1, 5);
INSERT INTO IORChannel VALUES('Vide VdF OK', 0, 1, 6);
INSERT INTO IORChannel VALUES('Not used 1', 0, 1, 7);
INSERT INTO IORChannel VALUES('Not used 2', 0, 2, 0);
INSERT INTO IORChannel VALUES('Not used 3', 0, 2, 1);
INSERT INTO IORChannel VALUES('Not used 4', 0, 2, 2);
INSERT INTO IORChannel VALUES('Not used 5', 0, 2, 3);
INSERT INTO IORChannel VALUES('Not used 6', 0, 2, 4);
INSERT INTO IORChannel VALUES('Not used 7', 0, 2, 5);
INSERT INTO IORChannel VALUES('Not used 8', 0, 2, 6);
INSERT INTO IORChannel VALUES('Not used 9', 0, 2, 7);

INSERT INTO IORChannel VALUES('Vanne B1', 1, 0, 0);
INSERT INTO IORChannel VALUES('Vanne B3', 1, 0, 1);
INSERT INTO IORChannel VALUES('Vanne B5', 1, 0, 2);
INSERT INTO IORChannel VALUES('Vanne B8', 1, 0, 3);
INSERT INTO IORChannel VALUES('Vanne B11', 1, 0, 4);
INSERT INTO IORChannel VALUES('Vanne B13', 1, 0, 5);
INSERT INTO IORChannel VALUES('PP1', 1, 0, 6);
INSERT INTO IORChannel VALUES('PP2', 1, 0, 7);
INSERT INTO IORChannel VALUES('TB1', 1, 1, 0);
INSERT INTO IORChannel VALUES('PC1', 1, 1, 1);
INSERT INTO IORChannel VALUES('PC2', 1, 1, 2);
INSERT INTO IORChannel VALUES('TB3', 1, 1, 3);
INSERT INTO IORChannel VALUES('Vanne B6', 1, 1, 4);
INSERT INTO IORChannel VALUES('Vanne B9', 1, 1, 5);
INSERT INTO IORChannel VALUES('Membrane OK', 1, 1, 6);
INSERT INTO IORChannel VALUES('Vide Cyclo D/L', 1, 1, 7);
INSERT INTO IORChannel VALUES('Not used 10', 1, 2, 0);
INSERT INTO IORChannel VALUES('Not used 11', 1, 2, 1);
INSERT INTO IORChannel VALUES('Not used 12', 1, 2, 2);
INSERT INTO IORChannel VALUES('Not used 13', 1, 2, 3);
INSERT INTO IORChannel VALUES('Not used 14', 1, 2, 4);
INSERT INTO IORChannel VALUES('Not used 15', 1, 2, 5);
INSERT INTO IORChannel VALUES('Not used 16', 1, 2, 6);
INSERT INTO IORChannel VALUES('Not used 17', 1, 2, 7);

INSERT INTO IORChannel VALUES('TBS1', 2, 0, 0);
INSERT INTO IORChannel VALUES('Vanne C4', 2, 0, 1);
INSERT INTO IORChannel VALUES('TBS2', 2, 0, 2);
INSERT INTO IORChannel VALUES('Not used 18', 2, 0, 3);
INSERT INTO IORChannel VALUES('Vanne CB', 2, 0, 4);
INSERT INTO IORChannel VALUES('Vide Source D/L', 2, 0, 5);
INSERT INTO IORChannel VALUES('Vide Cyclo OK', 2, 0, 6);
INSERT INTO IORChannel VALUES('Vide Source OK', 2, 0, 7);
INSERT INTO IORChannel VALUES('QZ1', 2, 1, 0);
INSERT INTO IORChannel VALUES('QZ2', 2, 1, 1);
INSERT INTO IORChannel VALUES('QZ3', 2, 1, 2);
INSERT INTO IORChannel VALUES('QZ4', 2, 1, 3);
INSERT INTO IORChannel VALUES('QZ5', 2, 1, 4);
INSERT INTO IORChannel VALUES('QZ6', 2, 1, 5);
INSERT INTO IORChannel VALUES('QZ7', 2, 1, 6);
INSERT INTO IORChannel VALUES('QZ8', 2, 1, 7);
INSERT INTO IORChannel VALUES('Not used 19', 2, 2, 0);
INSERT INTO IORChannel VALUES('Not used 20', 2, 2, 1);
INSERT INTO IORChannel VALUES('Not used 21', 2, 2, 2);
INSERT INTO IORChannel VALUES('Not used 22', 2, 2, 3);
INSERT INTO IORChannel VALUES('Not used 23', 2, 2, 4);
INSERT INTO IORChannel VALUES('Not used 24', 2, 2, 5);
INSERT INTO IORChannel VALUES('Not used 25', 2, 2, 6);
INSERT INTO IORChannel VALUES('Not used 26', 2, 2, 7);

INSERT INTO IORChannel VALUES('Not used 27', 3, 0, 0);
INSERT INTO IORChannel VALUES('Not used 28', 3, 0, 1);
INSERT INTO IORChannel VALUES('Not used 29', 3, 0, 2);
INSERT INTO IORChannel VALUES('Not used 30', 3, 0, 3);
INSERT INTO IORChannel VALUES('Not used 31', 3, 0, 4);
INSERT INTO IORChannel VALUES('Not used 32', 3, 0, 5);
INSERT INTO IORChannel VALUES('Not used 33', 3, 0, 6);
INSERT INTO IORChannel VALUES('Not used 34', 3, 0, 7);
INSERT INTO IORChannel VALUES('Not used 35', 3, 1, 0);
INSERT INTO IORChannel VALUES('Not used 36', 3, 1, 1);
INSERT INTO IORChannel VALUES('Not used 37', 3, 1, 2);
INSERT INTO IORChannel VALUES('Not used 38', 3, 1, 3);
INSERT INTO IORChannel VALUES('Not used 39', 3, 1, 4);
INSERT INTO IORChannel VALUES('Not used 40', 3, 1, 5);
INSERT INTO IORChannel VALUES('Not used 41', 3, 1, 6);
INSERT INTO IORChannel VALUES('Not used 42', 3, 1, 7);
INSERT INTO IORChannel VALUES('Not used 43', 3, 2, 0);
INSERT INTO IORChannel VALUES('Not used 44', 3, 2, 1);
INSERT INTO IORChannel VALUES('Not used 45', 3, 2, 2);
INSERT INTO IORChannel VALUES('Not used 46', 3, 2, 3);
INSERT INTO IORChannel VALUES('Not used 47', 3, 2, 4);
INSERT INTO IORChannel VALUES('Not used 48', 3, 2, 5);
INSERT INTO IORChannel VALUES('Not used 49', 3, 2, 6);
INSERT INTO IORChannel VALUES('Not used 50', 3, 2, 7);
