\c timeseries

CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE Measurement (
  time      TIMESTAMPTZ      NOT NULL,
  subsystem TEXT	   NOT NULL,
  channel    TEXT           NOT NULL,
  value DOUBLE PRECISION   NOT NULL,
  unit	TEXT 
);

CREATE TABLE CG_Measurement (
  time TIMESTAMPTZ NOT NULL,
  I_Arc_Source DOUBLE PRECISION NOT NULL,
  Temperature_EAU DOUBLE PRECISION NOT NULL,
  I_Extract_Source DOUBLE PRECISION NOT NULL,
  V_Extract_Source DOUBLE PRECISION NOT NULL,
  I_Filament_Source DOUBLE PRECISION NOT NULL,
  V_Filament_Source DOUBLE PRECISION NOT NULL,
  V_Arc_Source DOUBLE PRECISION NOT NULL,
  Temperature_Source DOUBLE PRECISION NOT NULL,
  Jauge_Source_Pe2 DOUBLE PRECISION NOT NULL,
  Jauge_Source_Pe3 DOUBLE PRECISION NOT NULL,
  Jauge_VdF_Pe20 DOUBLE PRECISION NOT NULL,
  Jauge_VdF_Pe21 DOUBLE PRECISION NOT NULL,
  Jauge_VdF_Pe24 DOUBLE PRECISION NOT NULL,
  Jauge_Cyclo_Pe4 DOUBLE PRECISION NOT NULL,
  Jauge_Cyclo_Pe5 DOUBLE PRECISION NOT NULL,
  I_Alstom DOUBLE PRECISION NOT NULL,
  V_Alstom DOUBLE PRECISION NOT NULL,
  V_HF1 DOUBLE PRECISION NOT NULL,
  V_HF2 DOUBLE PRECISION NOT NULL,
  Membrane_HF1 DOUBLE PRECISION NOT NULL,
  Membrane_HF2 DOUBLE PRECISION NOT NULL,
  Phase_HF1 DOUBLE PRECISION NOT NULL,
  Phase_HF2 DOUBLE PRECISION NOT NULL,
  Niveau_HF1 DOUBLE PRECISION NOT NULL,
  Niveau_HF2 DOUBLE PRECISION NOT NULL,
  Position_De1 DOUBLE PRECISION NOT NULL,
  Position_De2 DOUBLE PRECISION NOT NULL
);
  

SELECT create_hypertable('Measurement', 'time', chunk_time_interval => INTERVAL '7 days');
SELECT create_hypertable('CG_Measurement', 'time', chunk_time_interval => INTERVAL '7 days');


